### ISSUE TITLE
[Bug] Compiling Release Crash (Android)

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/XamarinCommunityToolkit#1228]
### Description

Hi,

we have problems with our Release. We link the project with "Sdk Assemblies Only" and using some Converters. In my ReproApp i only added the IsNotNullOrEmptyConverter. I'm not sure if this is the only converter which crashes and if only android affected.
Debug Configuration works. Release crashes.

### Steps to Reproduce

1. Open ReproApp
2. Use Release Configuration
3. Start Android App
4. App crashes

Logcat:

> Time	Device Name	Type	PID	Tag	Message
> 04-23 09:55:29.941	pixel_3_q_10_0_-_api_29	Error	2381	AndroidRuntime	android.runtime.JavaProxyThrowable: Xamarin.Forms.Xaml.XamlParseException: Position 4:3. Type xct:ListIsNotNullOrEmptyConverter not found in xmlns http://xamarin.com/schemas/2020/toolkit
>   at Xamarin.Forms.Xaml.CreateValuesVisitor.Visit (Xamarin.Forms.Xaml.ElementNode node, Xamarin.Forms.Xaml.INode parentNode) [0x0005f] in <d65bf1410bf6455f9040599eb74e34fa>:0 
>   at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x000ac] in <d65bf1410bf6455f9040599eb74e34fa>:0 
>   at Xamarin.Forms.Xaml.RootNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00079] in <d65bf1410bf6455f9040599eb74e34fa>:0 
>   at Xamarin.Forms.Xaml.XamlLoader.Visit (Xamarin.Forms.Xaml.RootNode rootnode, Xamarin.Forms.Xaml.HydrationContext visitorContext, System.Boolean useDesignProperties) [0x0006b] in <d65bf1410bf6455f9040599eb74e34fa>:0 
>   at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.String xaml, System.Reflection.Assembly rootAssembly, System.Boolean useDesignProperties) [0x000eb] in <d65bf1410bf6455f9040599eb74e34fa>:0 
>   at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.String xaml, System.Reflection.Assembly rootAssembly) [0x00000] in <d65bf1410bf6455f9040599eb74e34fa>:0 
>   at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml] (TXaml view, System.String xaml, System.Reflection.Assembly rootAssembly) [0x00000] in <d65bf1410bf6455f9040599eb74e34fa>:0 
>   at Xamarin.Forms.Xaml.ResourcesLoader.CreateFromResource[T] (System.String resourcePath, System.Reflection.Assembly assembly, System.Xml.IXmlLineInfo lineInfo) [0x000b9] in <d65bf1410bf6455f9040599eb74e34fa>:0 
>   at Xamarin.Forms.ResourceDictionary.SetAndLoadSource (System.Uri value, System.String resourcePath, System.Reflection.Assembly assembly, System.Xml.IXmlLineInfo lineInfo) [0x0006a] in <1150e8700ebb48ec95186d04c3b51da3>:0 
>   at ToolKitConverterCrash.App.InitializeComponent () [0x00109] in <4530f438b06b467590cf246fcd9a612c>:0 
>   at ToolKitConverterCrash.App..ctor () [0x00006] in <4530f438b06b467590cf246fcd9a612c>:0 
>   at ToolKitConverterCrash.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00015] in <3682a798eb3f4998a07602c118f73990>:0 
>   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <a7d9ec19c4fe40f7901a1983bf76cf74>:0 
>   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr,intptr)
> 	at crc6496d7e9e0d9adae0e.MainActivity.n_onCreate(Native Method)
> 	at crc6496d7e9e0d9adae0e.MainActivity.onCreate(Unknown Source:0)
> 	at android.app.Activity.performCreate(Activity.java:7802)
> 	at android.app.Activity.performCreate(Activity.java:7791)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
> 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 	at android.os.Looper.loop(Looper.java:214)
> 	at android.app.ActivityThread.main(ActivityThread.java:7356)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

### Basic Information

- Version with issue:1.1.0
- Last known good version:
- IDE:VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[ToolKitConverterCrash.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6364613/ToolKitConverterCrash.zip)

**Comment by pictos** [comment]
@AlleSchonWeg can you try to instantiate this converter in C#? you can do it on the App.xaml.cs ctor. Something like this:

```csharp
MainPage = new MainPage();
_ = new  Xamarin.CommunityToolkit.Converters.IsNotNullOrEmptyConverter();
```

**Comment by AlleSchonWeg** [comment]
Hi,
Not tested, but I'm sure that will work. At the moment we use a linker file and reference the converter types: https://docs.microsoft.com/de-de/xamarin/cross-platform/deploy-test/linker
This also works.
Are you able to reproduce the issue with my sample app?

**Comment by pictos** [comment]
@AlleSchonWeg not yet, I'll have time today night, I just want to have more info to know what I should look for (:
Thanks for the feedback, this is helpful

**Comment by AndreiMisiukevich** [comment]
Tested on provided sample "adding new IsNotNullOrEmptyConverter();" fixes the issue.

**Comment by AlleSchonWeg** [comment]
Hi @pictos and @AndreiMisiukevich, 😊
i can confirm, that adding 
`
_ = new IsNotNullOrEmptyConverter();
`
fixes the issue. But with this PR, XCT is marked as linkersafe: https://github.com/xamarin/XamarinCommunityToolkit/pull/210. 

Which is not true. Thanks for your work

**Comment by AndreiMisiukevich** [comment]
Yeah, there are some issues...very strange issues.
Frankly speaking, I am not sure whether it's fixable. Because you use it in xaml and linker cannot understand that this converter should not be removed...

**Comment by AlleSchonWeg** [comment]
Hi @AndreiMisiukevich,
i think there are three options. All not verified:
1. Use Preserve Attribute
2. Try xamlC https://github.com/xamarin/Xamarin.Forms/issues/8722
3. Implement an XF.Init(); function. Like Essentials do

Perhaps there other ways to make it linker safe.

**Comment by AndreiMisiukevich** [comment]
@AlleSchonWeg could you please check if xamlC resolves you issue?
If yes, then we will update our docs. I think, this is the best solution.

Both other might work, but they are not ideal (because a lot of unused stuff potentially would not be cut off the app, what is not great, I believe)

**Comment by AlleSchonWeg** [comment]
Hi,

i tested a litte bit and the xamlc was already defined in the AssemblyInfo.cs. So adding XamlC didn't change anything.
But i identified the problem. In the sample i use a separate ResourceDictionary (Converters.xaml) and added the file to the MergedDictionaries list in app.xaml.
The Converters.xaml file has no code behind file. But if i add the converters.xaml with a code behind file the linking works. Sample Converters.xaml:
```XAML
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms"
                    x:Class="ToolKitConverterCrash.Converters"
					xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
					xmlns:xct="http://xamarin.com/schemas/2020/toolkit">
	<xct:ListIsNotNullOrEmptyConverter x:Key="ListIsNotNullOrEmptyConverter" />
	<xct:IsNotNullOrEmptyConverter x:Key="IsNotNullOrEmptyConverter" />
</ResourceDictionary>
```
Sample Converters.xaml.cs
```C#
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace ToolKitConverterCrash
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Converters : ResourceDictionary
    {
        public Converters()
        {
            InitializeComponent();
        }
    }
}
```
This docs: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries#merged-resource-dictionaries mention that "a code-behind file isn't required" with local ResourceDictionarys. I'm not sure if the docs are wrong or this only works with styles.
I attached a working version:
[ToolKitConverterCrash.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6396786/ToolKitConverterCrash.zip)

**Comment by AndreiMisiukevich** [comment]
Interesting. Doesn't it mean that the problem in on XF side? (Code generation level)

I am not a linker expert, I guess need to gather ideas from people whom might have better understanding
CC @jsuarezruiz @jfversluis @StephaneDelcroix

**Comment by pictos** [comment]
My guess is because of reflection, if I'm not wrong the XAML parse to C#, is all reflection code, and the linker doesn't handle that very well. But good to know that scenario, thanks @AlleSchonWeg for that.
